// <auto-generated />
using System;
using CavaniVets.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CavaniVets.Api.Data.Migrations
{
    [DbContext(typeof(CavaniDbContext))]
    [Migration("20261007043519_LocalEnderecoEOrcamento")]
    partial class LocalEnderecoEOrcamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CavaniVets.Api.Domain.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Idade")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Peso")
                        .HasColumnType("text");

                    b.Property<string>("Raca")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Autorizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AceitoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AceitouLgpd")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitouResponsabilidadeFinanceira")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitouTermo")
                        .HasColumnType("boolean");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeAssinado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TextoTermoAceito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValoresExibidosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersaoTermoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("SolicitacaoId")
                        .IsUnique();

                    b.HasIndex("TutorId");

                    b.HasIndex("VersaoTermoId");

                    b.ToTable("Autorizacoes");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.ContaAzulConexao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AccessTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContaAzulConexoes");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreenchidoPor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.ItemPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContaAzulServicoId")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ItensPreco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "consulta",
                            Descricao = "Consulta oftalmológica inicial",
                            Grupo = "Agora",
                            Observacao = "Medicamentos para diagnóstico incluídos",
                            Ordem = 1,
                            Valor = 800m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "km",
                            Descricao = "Deslocamento",
                            Grupo = "Agora",
                            Observacao = "por km rodado, saindo da Rua Arandu, 885 (Brooklin Paulista), + pedágio. Se a rota for compartilhada com outros atendimentos, o deslocamento pode ser dividido.",
                            Ordem = 2,
                            Valor = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "materiais-diagnostico",
                            Descricao = "Materiais estéreis para diagnóstico",
                            Grupo = "Agora",
                            Observacao = "cobrados à parte, se usados",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "ultrassom",
                            Descricao = "Exame ultrassonográfico oftalmológico",
                            Grupo = "Indicados",
                            Ordem = 10,
                            Valor = 550m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Codigo = "acompanhamento",
                            Descricao = "Acompanhamento oftálmico, até a alta clínica",
                            Grupo = "Indicados",
                            Observacao = "por visita",
                            Ordem = 11,
                            Valor = 300m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Codigo = "medicamentos-tratamento",
                            Descricao = "Medicamentos e materiais para tratamento",
                            Grupo = "Indicados",
                            Observacao = "à parte",
                            Ordem = 12
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Codigo = "cirurgia",
                            Descricao = "Procedimentos cirúrgicos",
                            Grupo = "Indicados",
                            Observacao = "sob orçamento",
                            Ordem = 13
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Codigo = "inf-subconjuntival",
                            Descricao = "Subconjuntival",
                            Grupo = "Infiltrações",
                            Ordem = 20,
                            Valor = 350m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Codigo = "inf-retrobulbar",
                            Descricao = "Retrobulbar",
                            Grupo = "Infiltrações",
                            Ordem = 21,
                            Valor = 450m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Codigo = "inf-intravitrea",
                            Descricao = "Intravítrea",
                            Grupo = "Infiltrações",
                            Ordem = 22,
                            Valor = 700m
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Codigo = "inf-intralesional",
                            Descricao = "Intralesional",
                            Grupo = "Infiltrações",
                            Ordem = 23,
                            Valor = 750m
                        });
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DistanciaCalculadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DistanciaKmIda")
                        .HasPrecision(8, 1)
                        .HasColumnType("numeric(8,1)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<decimal?>("PedagioIda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<string>("AudioArquivo")
                        .HasColumnType("text");

                    b.Property<int?>("AudioDuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("ContaAzulOrcamentoId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Especie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Idade")
                        .HasColumnType("text");

                    b.Property<int?>("LocalId")
                        .HasColumnType("integer");

                    b.Property<string>("Medicacoes")
                        .HasColumnType("text");

                    b.Property<string>("Olho")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PetNome")
                        .HasColumnType("text");

                    b.Property<string>("PreenchidoPor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Prioridade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueixaHistorico")
                        .HasColumnType("text");

                    b.Property<string>("Raca")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenTutor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratadorCelular")
                        .HasColumnType("text");

                    b.Property<string>("TratadorNome")
                        .HasColumnType("text");

                    b.Property<string>("TutorCelular")
                        .HasColumnType("text");

                    b.Property<bool?>("TutorCienteCusto")
                        .HasColumnType("boolean");

                    b.Property<int?>("TutorId")
                        .HasColumnType("integer");

                    b.Property<string>("TutorNome")
                        .HasColumnType("text");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("VeterinarioRecebeRelatorios")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("LocalId");

                    b.HasIndex("Protocolo")
                        .IsUnique();

                    b.HasIndex("TokenTutor")
                        .IsUnique();

                    b.HasIndex("TutorId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("ContaAzulId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.VersaoTermo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Versao")
                        .IsUnique();

                    b.ToTable("VersoesTermo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = false,
                            Texto = "1. Autorizo a M.V. Juliane Cavani Pimentel (CRMV-SP 11.064), da Clínica Cavani Vets, a realizar consulta oftalmológica no animal {animal}, a pedido do médico-veterinário solicitante.\n2. Declaro estar ciente de que a consulta inicial custa R$ 800,00, com medicamentos para diagnóstico incluídos, acrescida das despesas de deslocamento (R$ 2,50 por km rodado + pedágio) e dos materiais estéreis para diagnóstico, se utilizados.\n3. Estou ciente da tabela de valores de exames, infiltrações e acompanhamento apresentada nesta página, e de que procedimentos adicionais, medicamentos de tratamento e cirurgias serão informados antes de sua realização.\n4. Assumo a responsabilidade pelo pagamento dos valores referentes ao atendimento do animal, nas condições informadas pela clínica.\n5. Estou ciente de que a medicina veterinária não é uma ciência exata e de que a resposta ao diagnóstico e ao tratamento varia de acordo com cada paciente.\n6. Autorizo o uso dos meus dados pessoais para cadastro, faturamento, emissão de documentos fiscais e comunicação sobre o atendimento, incluindo o compartilhamento com o veterinário solicitante e, quando necessário, com hospitais parceiros, conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018).\n7. Esta autorização é registrada eletronicamente com data, hora e dados do dispositivo utilizado, e vale como minha assinatura.",
                            Versao = "2026.1-rascunho",
                            VigenteDesde = new DateTimeOffset(new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Texto = "1. Autorizo a M.V. Juliane Cavani Pimentel (CRMV-SP 11.064), da Clínica Cavani Vets, a realizar consulta oftalmológica no animal {animal}, a pedido do médico-veterinário solicitante.\n2. Declaro estar ciente de que a consulta inicial custa R$ 800,00, com medicamentos para diagnóstico incluídos, acrescida das despesas de deslocamento e dos materiais estéreis para diagnóstico, se utilizados. O deslocamento custa R$ 2,50 por km rodado, contado a partir da Rua Arandu, 885, Brooklin Paulista, São Paulo, mais pedágio; quando a rota for compartilhada com outros atendimentos, o deslocamento poderá ser dividido entre eles.\n3. Estou ciente da tabela de valores de exames, infiltrações e acompanhamento apresentada nesta página, e de que procedimentos adicionais, medicamentos de tratamento e cirurgias serão informados antes de sua realização.\n4. Assumo a responsabilidade pelo pagamento dos valores referentes ao atendimento do animal, nas condições informadas pela clínica.\n5. Estou ciente de que a medicina veterinária não é uma ciência exata e de que a resposta ao diagnóstico e ao tratamento varia de acordo com cada paciente.\n6. Autorizo o uso dos meus dados pessoais para cadastro, faturamento, emissão de documentos fiscais e comunicação sobre o atendimento, incluindo o compartilhamento com o veterinário solicitante e, quando necessário, com hospitais parceiros, conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018).\n7. Esta autorização é registrada eletronicamente com data, hora e dados do dispositivo utilizado, e vale como minha assinatura.",
                            Versao = "2026.2-rascunho",
                            VigenteDesde = new DateTimeOffset(new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Animal", b =>
                {
                    b.HasOne("CavaniVets.Api.Domain.Tutor", "Tutor")
                        .WithMany("Animais")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Autorizacao", b =>
                {
                    b.HasOne("CavaniVets.Api.Domain.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavaniVets.Api.Domain.Solicitacao", "Solicitacao")
                        .WithOne("Autorizacao")
                        .HasForeignKey("CavaniVets.Api.Domain.Autorizacao", "SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavaniVets.Api.Domain.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavaniVets.Api.Domain.VersaoTermo", "VersaoTermo")
                        .WithMany()
                        .HasForeignKey("VersaoTermoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Solicitacao");

                    b.Navigation("Tutor");

                    b.Navigation("VersaoTermo");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Solicitacao", b =>
                {
                    b.HasOne("CavaniVets.Api.Domain.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("CavaniVets.Api.Domain.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.HasOne("CavaniVets.Api.Domain.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId");

                    b.HasOne("CavaniVets.Api.Domain.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Local");

                    b.Navigation("Tutor");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Solicitacao", b =>
                {
                    b.Navigation("Autorizacao");
                });

            modelBuilder.Entity("CavaniVets.Api.Domain.Tutor", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
